<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Base\\Hdb' => $baseDir . '/generated-classes/Base/Hdb.php',
    'Base\\HdbQuery' => $baseDir . '/generated-classes/Base/HdbQuery.php',
    'Base\\Listing' => $baseDir . '/generated-classes/Base/Listing.php',
    'Base\\ListingQuery' => $baseDir . '/generated-classes/Base/ListingQuery.php',
    'Base\\LoginSession' => $baseDir . '/generated-classes/Base/LoginSession.php',
    'Base\\LoginSessionQuery' => $baseDir . '/generated-classes/Base/LoginSessionQuery.php',
    'Base\\NormalUser' => $baseDir . '/generated-classes/Base/NormalUser.php',
    'Base\\NormalUserQuery' => $baseDir . '/generated-classes/Base/NormalUserQuery.php',
    'Base\\Photo' => $baseDir . '/generated-classes/Base/Photo.php',
    'Base\\PhotoQuery' => $baseDir . '/generated-classes/Base/PhotoQuery.php',
    'Base\\Realtor' => $baseDir . '/generated-classes/Base/Realtor.php',
    'Base\\RealtorQuery' => $baseDir . '/generated-classes/Base/RealtorQuery.php',
    'Base\\User' => $baseDir . '/generated-classes/Base/User.php',
    'Base\\UserQuery' => $baseDir . '/generated-classes/Base/UserQuery.php',
    'Base\\Watchlist' => $baseDir . '/generated-classes/Base/Watchlist.php',
    'Base\\WatchlistQuery' => $baseDir . '/generated-classes/Base/WatchlistQuery.php',
    'Hdb' => $baseDir . '/generated-classes/Hdb.php',
    'HdbQuery' => $baseDir . '/generated-classes/HdbQuery.php',
    'Listing' => $baseDir . '/generated-classes/Listing.php',
    'ListingQuery' => $baseDir . '/generated-classes/ListingQuery.php',
    'LoginSession' => $baseDir . '/generated-classes/LoginSession.php',
    'LoginSessionQuery' => $baseDir . '/generated-classes/LoginSessionQuery.php',
    'Map\\HdbTableMap' => $baseDir . '/generated-classes/Map/HdbTableMap.php',
    'Map\\ListingTableMap' => $baseDir . '/generated-classes/Map/ListingTableMap.php',
    'Map\\LoginSessionTableMap' => $baseDir . '/generated-classes/Map/LoginSessionTableMap.php',
    'Map\\NormalUserTableMap' => $baseDir . '/generated-classes/Map/NormalUserTableMap.php',
    'Map\\PhotoTableMap' => $baseDir . '/generated-classes/Map/PhotoTableMap.php',
    'Map\\RealtorTableMap' => $baseDir . '/generated-classes/Map/RealtorTableMap.php',
    'Map\\UserTableMap' => $baseDir . '/generated-classes/Map/UserTableMap.php',
    'Map\\WatchlistTableMap' => $baseDir . '/generated-classes/Map/WatchlistTableMap.php',
    'NormalUser' => $baseDir . '/generated-classes/NormalUser.php',
    'NormalUserQuery' => $baseDir . '/generated-classes/NormalUserQuery.php',
    'Photo' => $baseDir . '/generated-classes/Photo.php',
    'PhotoQuery' => $baseDir . '/generated-classes/PhotoQuery.php',
    'Realtor' => $baseDir . '/generated-classes/Realtor.php',
    'RealtorQuery' => $baseDir . '/generated-classes/RealtorQuery.php',
    'User' => $baseDir . '/generated-classes/User.php',
    'UserQuery' => $baseDir . '/generated-classes/UserQuery.php',
    'Watchlist' => $baseDir . '/generated-classes/Watchlist.php',
    'WatchlistQuery' => $baseDir . '/generated-classes/WatchlistQuery.php',
);
